name: Flake8 Check

on:
  push:
    branches: [ main ]  # ou substitua 'main' pelo nome da sua branch principal
  pull_request:
    branches: [ main ]  # ou substitua 'main' pelo nome da sua branch principal

jobs:
  flake8:
    name: Run Flake8
    runs-on: ubuntu-latest  # ou escolha o sistema operacional de sua preferência

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # substitua 'x' pela versão do Python que seu projeto utiliza

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    
    - name: Run Flake8
      run: |
        flake8 .